### ISSUE TITLE
Exception when loading MatterController

### ISSUE THREAD

**Issue by Nik19792000** [FezVrasta/node-red-matter#11]
Hi, I played around with node-red-matter, and I was even able to add one Device to Google Home, but shortly afterwards, Node Red failed to restart due to the following error:
```
1 Jan 12:03:45 - [info] [matter-server:MatterServer] Starting matter server
1 Jan 12:03:45 - [info] [matter-server:MatterServer] Added commissioning controller for 7e8198ecd6d4ee69
1 Jan 12:03:45 - [info] [matter-server:MatterServer] All related nodes added (1/1)
1 Jan 12:03:45 - [info] [matter-server:MatterServer] Starting matter server
1 Jan 12:03:45 - [info] Started modified flows
1 Jan 12:04:00 - [red] Uncaught Exception:
1 Jan 12:04:00 - [error] Error: No device discovered using identifier {"shortDiscriminator":15}! Please check that the relevant device is online.
    at MatterController.<anonymous> (/config/node_modules/@project-chip/matter.js/src/MatterController.ts:181:19)
    at Generator.next (<anonymous>)
    at fulfilled (/config/node_modules/@project-chip/matter.js/dist/cjs/MatterController.js:10:58)
[12:04:00] INFO: Service Node-RED exited with code 1 (by signal 0)
```

I re-installed node-red-matter and I can narrow it down to just adding a MatterControllerStatusNode and defining a MatterController and MatterServer. As soon as I do this, I get this error. Any idea, what's the problem?

**Comment by Nik19792000** [comment]
I guess, I misinterpreted the purpose of the MatterController node. If I only want to create virtual Matter devices in NodeRed, then I shouldn't use MatterController node, right?
It's still a bit ideal to have the whole thing crash, if I pick a wrong node. I had to start NodeRed in safe mode to be able to delete the node.

**Comment by Apollon77** [comment]
Correct, The MatterController is used to pair with a matter device

**Comment by Apollon77** [comment]
Bu tin fact yes the code need to catch the error ideally :-)

**Comment by FezVrasta** [comment]
Do you have a configuration to share to reproduce the crash?

**Comment by Nik19792000** [comment]
You can just add a Matter Controller Status node. Then add a new Matter Controller and use a valid pairing code (e.g. 749701123365521327694). When you deploy the flow, the error will show and node-red will stop.

**Comment by macinspak** [comment]
I'd love to help with this issue, however, on a clean clone of the repo, I run npm i and nom build and get the following error:

```
node_modules/buffer/index.d.ts:1:14 - error TS2417: Class static side 'typeof Buffer' incorrectly extends base class static side '{ readonly prototype: Uint8Array; readonly BYTES_PER_ELEMENT: number; of(...items: number[]): Uint8Array; from(arrayLike: ArrayLike<number>): Uint8Array; from<T>(arrayLike: ArrayLike<...>, mapfn: (v: T, k: number) => number, thisArg?: any): Uint8Array; from(arrayLike: Iterable<...>, mapfn?: ((v: number, k: number) =...'.
  Types of property 'concat' are incompatible.
    Type '(list: Uint8Array[], totalLength?: number | undefined) => Buffer' is not assignable to type '(...arrays: Uint8Array[]) => Uint8Array'.
      Types of parameters 'list' and 'arrays' are incompatible.
        Type 'Uint8Array' is missing the following properties from type 'Uint8Array[]': pop, push, concat, shift, and 5 more.

1 export class Buffer extends Uint8Array {
               ~~~~~~


Found 1 error in node_modules/buffer/index.d.ts:1
```

I tried experimenting with node versions and also updating dependencies, but I am having trouble narrowing it down.

I'm currently on node 18.12.1 and rpm 8.19.4
I need to use/extend these nodes to link my node-red home automation to some new matter devices and I have hit this issue #11, so happy to fix it, but am currently stuck

Thanks for your comment
